spring:
  application:
    name: service-registry

  cloud:
    config:
      enabled: false   # Disable Spring Cloud Config since we are not using it

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
